### ISSUE TITLE
Unable to Preview in ST3

### ISSUE THREAD

**Issue by gsingh93** [iafan/SublimeTextPreview#2]
The Preview option in tools is greyed out when trying to preview an html file in ST3 using Ubuntu 13.04.

**Comment by iafan** [comment]
Thanks for reporting. I made the plugin compatible as of https://github.com/iafan/SublimeTextPreview/commit/d25f43ef8991970ccef9f54a86ea98ce939a25f7

You may need to load it from GitHub and update it in the ST3 plugins folder manually.
